apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result-service
    app: demo-result-app
spec:
  selector:
    name: result-app-pod
    app: demo-result-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005

  type: NodePort